services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www/default
      - ../../csv-format:/var/www/csv
      - ../../oop:/var/www/oop
  nginx:
   image: nginx:1.27-alpine
   container_name: nginx
   restart: always
   ports:
    - "8000:80"
   volumes:
    - ../src:/var/www/default
    - ../../csv-format:/var/www/csv
    - ../../oop:/var/www/oop
    - ./nginx:/etc/nginx/conf.d