services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
  nginx:
   image: nginx:1.27-alpine
   container_name: nginx
   restart: always
   ports:
    - "8000:80"
   volumes:
    - ../src:/var/www
    - ./nginx:/etc/nginx/conf.d
  db:
    image: mysql:8.0
    container_name: sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./storage/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1